// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/change-password": {
            "post": {
                "description": "Ushbu endpoint foydalanuvchining parolini o'zgartiradi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Parolni o'zgartirish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Access token",
                        "name": "Acces-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Parolni o'zgartirish uchun foydalanuvchi ma'lumotlari",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ChangePassReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Parol muvaffaqiyatli o'zgartirildi",
                        "schema": {
                            "$ref": "#/definitions/model.ChangePassResp"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Ushbu endpoint foydalanuvchining email va parolini tekshiradi va access hamda refresh tokenlarini qaytaradi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Foydalanuvchi tizimga kirishi",
                "parameters": [
                    {
                        "description": "Kirish ma'lumotlari (email va parol)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Access va Refresh tokenlar qaytarildi",
                        "schema": {
                            "$ref": "#/definitions/model.LoginResp"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Server xatosi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Ushbu endpoint foydalanuvchini tizimdan chiqaradi va access tokenni blacklisting ro'yxatiga qo'shadi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Tizimdan chiqish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Access token",
                        "name": "Acces-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tizimdan muvaffaqiyatli chiqdingiz, biz sizni yana kutamiz.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Ushbu endpoint foydalanuvchini ro'yxatdan o'tkazadi. Email va parol bilan ma'lumotlarni yuboring.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Foydalanuvchini ro'yxatdan o'tkazish",
                "parameters": [
                    {
                        "description": "Ro'yxatdan o'tish ma'lumotlari",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Foydalanuvchi muvaffaqiyatli ro'yxatdan o'tkazildi",
                        "schema": {
                            "$ref": "#/definitions/model.RegisterResp"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    },
                    "500": {
                        "description": "Server xatosi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "post": {
                "description": "Ushbu endpoint foydalanuvchining parolini qayta tiklaydi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Parolni qayta tiklash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Access token",
                        "name": "Acces-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Yangi parol",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Parol muvaffaqiyatli tiklandi",
                        "schema": {
                            "$ref": "#/definitions/model.ResetPassResp"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/user/deleteFollower/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint orqali foydalanuvchidan kuzatuvchini o'chirishingiz mumkin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Foydalanuvchidan kuzatuvchini o'chirish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token bilan birga keladi",
                        "name": "Athorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "O'chirilishi kerak bo'lgan kuzatuvchi IDsi",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Kuzatuvchini muvaffaqiyatli o'chirdi",
                        "schema": {
                            "$ref": "#/definitions/users.Massage"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/user/deleteUser{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint ma'lum bir foydalanuvchini ID orqali o'chirish uchun ishlatiladi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Foydalanuvchini o'chirish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Foydalanuvchi IDsi",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Foydalanuvchi muvaffaqiyatli o'chirildi",
                        "schema": {
                            "$ref": "#/definitions/users.Massage"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/user/followers": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint orqali foydalanuvchining kuzatuvchilarini ro'yxatini olish mumkin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Foydalanuvchining kuzatuvchilarini olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token bilan birga keladi",
                        "name": "Athorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Qaysi sahifani ko'rmoqchisiz? Default: 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Bir sahifada nechta element bo'lishi kerak? Default: 10",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Foydalanuvchining kuzatuvchilar ro'yxati",
                        "schema": {
                            "$ref": "#/definitions/users.GetaFollowersRes"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/user/following": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint orqali ma'lum bir foydalanuvchining kimlarni kuzatayotganini olish mumkin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Foydalanuvchi kimlarni kuzatayotganini olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token bilan birga keladi",
                        "name": "Athorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Sahifa raqami",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Sahifadagi elementlar soni",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Kuzatadigan foydalanuvchilar ro'yxati",
                        "schema": {
                            "$ref": "#/definitions/users.GetaFollowingRes"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/user/getFollower/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint orqali ma'lum bir kuzatuvchining ma'lumotlarini olish mumkin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Kuzatuvchi ma'lumotlarini olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token bilan birga keladi",
                        "name": "Athorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Kuzatuvchi IDsi",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Kuzatuvchi ma'lumotlari",
                        "schema": {
                            "$ref": "#/definitions/users.Follow"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/user/getUsers": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint mavjud foydalanuvchilar ro'yxatini olish uchun ishlatiladi. Ro'yxat sahifalash orqali cheklangan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Foydalanuvchilarni olish",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Sahifa raqami, default: 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Har bir sahifadagi foydalanuvchilar soni, default: 10",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Foydalanuvchilar ro'yxati muvaffaqiyatli qaytarildi",
                        "schema": {
                            "$ref": "#/definitions/users.GetUserRes"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/user/getUser{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint ma'lum bir foydalanuvchini ID orqali olish uchun ishlatiladi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Foydalanuvchini ID orqali olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Foydalanuvchi IDsi",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Foydalanuvchi ma'lumotlari muvaffaqiyatli olindi",
                        "schema": {
                            "$ref": "#/definitions/users.User"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/user/subscribe": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint orqali foydalanuvchi boshqa foydalanuvchini kuzatishi mumkin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Foydalanuvchini kuzatish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token bilan birga keladi",
                        "name": "Athorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Kuzatilayotgan foydalanuvchi IDsi",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Kuzatish muvaffaqiyatli amalga oshirildi",
                        "schema": {
                            "$ref": "#/definitions/users.Massage"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/users/deleteFollowing/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint orqali ma'lum bir foydalanuvchining kuzatayotgan boshqa foydalanuvchisini o'chirish mumkin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Foydalanuvchi kuzatayotgan foydalanuvchini o'chirish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token bilan birga keladi",
                        "name": "Athorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Kuzatishni to'xtatmoqchi bo'lgan foydalanuvchi ID'si",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "O'chirish muvaffaqiyatli amalga oshirildi",
                        "schema": {
                            "$ref": "#/definitions/users.Massage"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        },
        "/users/getFollowing/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ushbu endpoint orqali ma'lum bir foydalanuvchining kimni kuzatayotganini ID orqali olish mumkin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Foydalanuvchi kimni kuzatayotganini ID orqali olish",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token bilan birga keladi",
                        "name": "Athorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Kuzatmoqchi bo'lgan foydalanuvchi ID'si",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Kuzatmoqchi bo'lgan foydalanuvchining ma'lumotlari",
                        "schema": {
                            "$ref": "#/definitions/users.Follow"
                        }
                    },
                    "400": {
                        "description": "Xatolik yuz berdi",
                        "schema": {
                            "$ref": "#/definitions/model.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ChangePassReq": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "now_password": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.ChangePassResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.LoginReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "model.LoginResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "model.RegisterReq": {
            "type": "object",
            "properties": {
                "emil": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.RegisterResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.ResetPassResp": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "users.Follow": {
            "type": "object",
            "properties": {
                "birth_day": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "users.Followers": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "follower_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "users.Following": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "following_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "users.GetUserRes": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/users.User"
                    }
                }
            }
        },
        "users.GetaFollowersRes": {
            "type": "object",
            "properties": {
                "followers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/users.Followers"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                }
            }
        },
        "users.GetaFollowingRes": {
            "type": "object",
            "properties": {
                "following": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/users.Following"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                }
            }
        },
        "users.Massage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "users.User": {
            "type": "object",
            "properties": {
                "birth_day": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "AuthService API",
	Description:      "Auth service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
