definitions:
  model.ChangePassReq:
    properties:
      new_password:
        type: string
      now_password:
        type: string
      user_id:
        type: string
    type: object
  model.ChangePassResp:
    properties:
      message:
        type: string
    type: object
  model.Error:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  model.ForgotPassReq:
    properties:
      email:
        type: string
    type: object
  model.ForgotPassResp:
    properties:
      message:
        type: string
    type: object
  model.LoginReq:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.LoginResp:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  model.RegisterReq:
    properties:
      emil:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  model.RegisterResp:
    properties:
      id:
        type: string
      message:
        type: string
    type: object
  model.ResetPassResp:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: Auth service
  title: AuthService API
  version: "1.0"
paths:
  /auth/change-password:
    post:
      consumes:
      - application/json
      description: Ushbu endpoint foydalanuvchining parolini o'zgartiradi.
      parameters:
      - description: Access token
        in: header
        name: Acces-Token
        required: true
        type: string
      - description: Parolni o'zgartirish uchun foydalanuvchi ma'lumotlari
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ChangePassReq'
      produces:
      - application/json
      responses:
        "200":
          description: Parol muvaffaqiyatli o'zgartirildi
          schema:
            $ref: '#/definitions/model.ChangePassResp'
        "400":
          description: Xatolik yuz berdi
          schema:
            $ref: '#/definitions/model.Error'
      summary: Parolni o'zgartirish
      tags:
      - Authentication
  /auth/forgot-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: Forgot Password
        in: body
        name: Email
        required: true
        schema:
          $ref: '#/definitions/model.ForgotPassReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ForgotPassResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Error'
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Forgot password parol esdan chiqqanda
      tags:
      - Authentication
  /auth/login:
    post:
      consumes:
      - application/json
      description: Ushbu endpoint foydalanuvchining email va parolini tekshiradi va
        access hamda refresh tokenlarini qaytaradi.
      parameters:
      - description: Kirish ma'lumotlari (email va parol)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: Access va Refresh tokenlar qaytarildi
          schema:
            $ref: '#/definitions/model.LoginResp'
        "400":
          description: Xatolik yuz berdi
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Server xatosi
          schema:
            $ref: '#/definitions/model.Error'
      summary: Foydalanuvchi tizimga kirishi
      tags:
      - Authentication
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Ushbu endpoint foydalanuvchini tizimdan chiqaradi va access tokenni
        blacklisting ro'yxatiga qo'shadi.
      parameters:
      - description: Access token
        in: header
        name: Acces-Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Tizimdan muvaffaqiyatli chiqdingiz, biz sizni yana kutamiz.
          schema:
            type: string
        "400":
          description: Xatolik yuz berdi
          schema:
            $ref: '#/definitions/model.Error'
      summary: Tizimdan chiqish
      tags:
      - Authentication
  /auth/register:
    post:
      consumes:
      - application/json
      description: Ushbu endpoint foydalanuvchini ro'yxatdan o'tkazadi. Email va parol
        bilan ma'lumotlarni yuboring.
      parameters:
      - description: Ro'yxatdan o'tish ma'lumotlari
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: Foydalanuvchi muvaffaqiyatli ro'yxatdan o'tkazildi
          schema:
            $ref: '#/definitions/model.RegisterResp'
        "400":
          description: Xatolik yuz berdi
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Server xatosi
          schema:
            $ref: '#/definitions/model.Error'
      summary: Foydalanuvchini ro'yxatdan o'tkazish
      tags:
      - Authentication
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Ushbu endpoint foydalanuvchining parolini qayta tiklaydi.
      parameters:
      - description: Access token
        in: header
        name: Acces-Token
        required: true
        type: string
      - description: Yangi parol
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Parol muvaffaqiyatli tiklandi
          schema:
            $ref: '#/definitions/model.ResetPassResp'
        "400":
          description: Xatolik yuz berdi
          schema:
            $ref: '#/definitions/model.Error'
      summary: Parolni qayta tiklash
      tags:
      - Authentication
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
